name: 'BigLinux Package XanMod'
description: 'Builds Manjaro Packages'

inputs:
  chave:
    description: 'token for webhooks'
    required: false

runs:
  using: "composite"
  steps:
    - name: install build-dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install \
        build-essential \
        cmake \
        fakeroot \
        git \
        libarchive-dev \
        libarchive-tools \
        libcurl4-openssl-dev \
        libgpgme-dev \
        libssl-dev \
        zip \
        python3-pip
        sudo pip3 install meson
        sudo pip3 install ninja
    - name: install pacman
      shell: bash
      env:
        PACMAN_VERSION: 6.0.1
      run: |
        sudo git clone --depth 1 https://gitlab.manjaro.org/packages/core/pacman.git
        pushd pacman
        sudo wget https://sources.archlinux.org/other/pacman/pacman-${PACMAN_VERSION}.tar.xz
        sudo tar -xvf pacman-${PACMAN_VERSION}.tar.xz
        pushd pacman-${PACMAN_VERSION}
        sudo patch -p1 -i ../pacman-sync-first-option.patch
        sudo meson --prefix=/usr \
                    --buildtype=plain \
                    -Ddoc=disabled \
                    -Ddoxygen=enabled \
                    -Dscriptlet-shell=/usr/bin/bash \
                    -Dldconfig=/usr/bin/ldconfig \
                    build
        sudo meson compile -C build
        sudo meson install -C build
        popd
        sudo install -m644 pacman.conf /etc/pacman.conf
        sudo install -m644 makepkg.conf /etc/
        sudo mkdir -p /etc/pacman.d
        sudo touch /etc/pacman.d/mirrorlist
        popd
        sudo rm -rf pacman
        
        #add biglinux repository
        sudo sed -i '/\[core\]/{h;s/.*/\[biglinux-update-stable\]/;p;x;}' /etc/pacman.conf
        sudo sed -i '/\[core\]/{h;s/.*/SigLevel = PackageRequired/;p;x;}' /etc/pacman.conf
        sudo sed -i '/\[core\]/{h;s/.*/Server = https:\/\/repo.biglinux.com.br\/update-stable\/$arch/;p;x;}' /etc/pacman.conf
        sudo sed -i '/\[core\]/{h;s/.*//;p;x;}' /etc/pacman.conf
        echo '
        [biglinux-stable]
        SigLevel = PackageRequired
        Server = https://repo.biglinux.com.br/stable/$arch' | sudo tee -a /etc/pacman.conf
        
        echo 'Server = https://manjaro.repo.cure.edu.uy/stable/$repo/$arch
        Server = http://mirror.datacenter.by/pub/mirrors/manjaro/stable/$repo/$arch
        Server = https://forksystems.mm.fcix.net/manjaro/stable/$repo/$arch
        Server = http://mirror.fcix.net/manjaro/stable/$repo/$arch
        Server = https://manjaro.ipacct.com/manjaro/stable/$repo/$arch
        Server = https://mirrors.gethosted.online/manjaro/repos/stable/$repo/$arch
        Server = https://ftp.caliu.cat/pub/distribucions/manjaro/stable/$repo/$arch
        Server = https://mirrors.tuna.tsinghua.edu.cn/manjaro/stable/$repo/$arch' | sudo tee -a /etc/pacman.d/mirrorlist
        
        sudo pacman -Sy
    
    - name: install keyrings
      shell: bash
      run: |
        sudo install -dm755 /usr/share/pacman/keyrings/
        sudo git clone --depth 1 https://gitlab.manjaro.org/packages/core/manjaro-keyring.git
        pushd manjaro-keyring
          sudo install -m0644 manjaro.gpg /usr/share/pacman/keyrings/
          sudo install -m0644 manjaro-trusted /usr/share/pacman/keyrings/
          sudo install -m0644 manjaro-trusted /usr/share/pacman/keyrings/
        popd
        sudo rm -rf manjaro-keyring
        mkdir -p archlinux-keyring
        pushd archlinux-keyring
          wget https://archlinux.org/packages/core/any/archlinux-keyring/download -O /tmp/archlinux-keyring.tar.zst
          tar --use-compress-program=unzstd --strip-components=4 --wildcards -xvf /tmp/archlinux-keyring.tar.zst usr/share/pacman/keyrings/*
          sudo install -m0644 archlinux.gpg /usr/share/pacman/keyrings/
          sudo install -m0644 archlinux-trusted /usr/share/pacman/keyrings/
          sudo install -m0644 archlinux-revoked /usr/share/pacman/keyrings/
        popd
        sudo rm -rf archlinux-keyring
        sudo pacman-key --init
        sudo pacman-key -r 45EC44879815E2A6
        sudo pacman-key --lsign-key 45EC44879815E2A6
        sudo pacman-key --populate archlinux manjaro
        
    - name: Send Hooks
      shell: bash
      run: |
          #bash -x xanmod.sh
          webhooks=$(curl -X POST -H "Accept: application/json" -H "Authorization: token ${{ inputs.chave }}" --data '{"event_type": "AUR/linux-xanmod", "client_payload": { "pkgbuild": "", "branch": stable, "url": "https://aur.archlinux.org/$xanmod", "version": "1.2.3"}}' https://api.github.com/repos/BigLinux-Package-Build/build-package/dispatches)


          ### STABLE ##
          #major=$(curl -s https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=linux-xanmod | sed 's/<[^>]*>//g' | grep _major= | cut -d "=" -f2 | sed 's|\.||g' | sed 's|-||g')
          #pkgver=$(curl -s https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=linux-xanmod | sed 's/<[^>]*>//g' | grep pkgver= | cut -d "=" -f2 | sed 's|\.||g' | sed 's|-||g' | cut -d "}" -f2)
          #pkgrel=$(curl -s https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=linux-xanmod | sed 's/<[^>]*>//g' | grep xanmod= | cut -d "=" -f2 | sed 's|\.||g' | sed 's|-||g')
          #versite=$major$pkgver$pkgrel

          #verrepo=$(pacman -Ss xanmod | grep biglinux-stable | grep -v headers | egrep -v "lts|rt|tt|edge" | cut -d " " -f2  | sed 's/\.//g' | sed 's/\-//')

          #if [ "$versite" -gt "$verrepo" ]; then
              #echo "Envia xanmod stable"
              #xanmod=linux-xanmod
              #$webhooks
          #fi

          ### EDGE ##
          #major=$(curl -s https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=linux-xanmod-edge | sed 's/<[^>]*>//g' | grep _major= | cut -d "=" -f2 | sed 's|\.||g' | sed 's|-||g')
          #pkgver=$(curl -s https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=linux-xanmod-edge | sed 's/<[^>]*>//g' | grep pkgver= | cut -d "=" -f2 | sed 's|\.||g' | sed 's|-||g' | cut -d "}" -f2)
          #pkgrel=$(curl -s https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=linux-xanmod-edge | sed 's/<[^>]*>//g' | grep xanmod= | cut -d "=" -f2 | sed 's|\.||g' | sed 's|-||g')
          #edgeversite=$major$pkgver$pkgrel

          #edgeverrepo=$(pacman -Ss xanmod | grep biglinux-stable | grep -v headers | egrep -v "lts|rt|tt" | grep edge | cut -d " " -f2  | sed 's/\.//g' | sed 's/\-//')

          #if [ "$edgeversite" -gt "$edgeverrepo" ]; then
              #echo "Envia edge"
              #xanmod=linux-xanmod-edge
              #$webhooks
          #fi

          ### LTS ##
          #major=$(curl -s https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=linux-xanmod-lts | sed 's/<[^>]*>//g' | grep _major= | cut -d "=" -f2 | sed 's|\.||g' | sed 's|-||g')
          #pkgver=$(curl -s https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=linux-xanmod-lts | sed 's/<[^>]*>//g' | grep pkgver= | cut -d "=" -f2 | sed 's|\.||g' | sed 's|-||g' | cut -d "}" -f2)
          #pkgrel=$(curl -s https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=linux-xanmod-lts | sed 's/<[^>]*>//g' | grep xanmod= | cut -d "=" -f2 | sed 's|\.||g' | sed 's|-||g')
          #ltsversite=$major$pkgver$pkgrel

          #ltsverrepo=$(pacman -Ss xanmod | grep biglinux-stable | grep -v headers | egrep -v "edge|rt|tt" | grep lts | cut -d " " -f2  | sed 's/\.//g' | sed 's/\-//')

          #if [ "$ltsversite" -gt "$ltsverrepo" ]; then
              #echo "Envia lts"
              #xanmod=linux-xanmod-lts
              #$webhooks
          #fi

          ### RT ##
          #major=$(curl -s https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=linux-xanmod-rt | sed 's/<[^>]*>//g' | grep _major= | cut -d "=" -f2 | sed 's|\.||g' | sed 's|-||g')
          #pkgver=$(curl -s https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=linux-xanmod-rt | sed 's/<[^>]*>//g' | grep pkgver= | cut -d "=" -f2 | sed 's|\.||g' | sed 's|-||g' | cut -d "}" -f2)
          #pkgrel=$(curl -s https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=linux-xanmod-rt | sed 's/<[^>]*>//g' | grep xanmod= | cut -d "=" -f2 | sed 's|\.||g' | sed 's|-||g')
          #rtversite=$major$pkgver$pkgrel

          #rtverrepo=$(pacman -Ss xanmod | grep biglinux-stable | grep -v headers | egrep -v "lts|edge|tt" | grep rt | cut -d " " -f2  | sed 's/\.//g' | sed 's/\-//')

          #if [ "$rtversite" -gt "$rtverrepo" ]; then
              #echo "Envia rt"
              #xanmod=linux-xanmod-rt
              #$webhooks
          #fi

          ### RT ##
          #major=$(curl -s https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=linux-xanmod-tt | sed 's/<[^>]*>//g' | grep _major= | cut -d "=" -f2 | sed 's|\.||g' | sed 's|-||g')
          #pkgver=$(curl -s https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=linux-xanmod-tt | sed 's/<[^>]*>//g' | grep pkgver= | cut -d "=" -f2 | sed 's|\.||g' | sed 's|-||g' | cut -d "}" -f2)
          #pkgrel=$(curl -s https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=linux-xanmod-tt | sed 's/<[^>]*>//g' | grep xanmod= | cut -d "=" -f2 | sed 's|\.||g' | sed 's|-||g')
          #ttversite=$major$pkgver$pkgrel

          #ttverrepo=$(pacman -Ss xanmod | grep biglinux-stable | grep -v headers | egrep -v "lts|edge|rt" | grep tt | cut -d " " -f2  | sed 's/\.//g' | sed 's/\-//')

          #if [ "$ttversite" -gt "$ttverrepo" ]; then
              #echo "Envia tt"
              #xanmod=linux-xanmod-tt
              #$webhooks
          #fi

          xanmod=linux-xanmod
          $webhooks
          
    ## Tmate ##
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
        
        
    
