name: BigLinux Hooks AUR STABLE

# Controls when the workflow will run
on:
  schedule:
    - cron:  '30 2 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - uses: actions/checkout@v2
      - name: Add Repo BigLinux
        run: |
          echo '
          [biglinux-stable]
          SigLevel = PackageRequired
          Server = https://repo.biglinux.com.br/stable/$arch' | sudo tee -a /etc/pacman.conf
          
          echo '
          [biglinux-testing]
          SigLevel = PackageRequired
          Server = https://repo.biglinux.com.br/testing/$arch' | sudo tee -a /etc/pacman.conf
          
          sudo pacman-key -r 45EC44879815E2A6
          sudo pacman-key --lsign-key 45EC44879815E2A6
          
      - name: Send WeebHooks
        run: |
          sudo pacman -Sy
          find -type f -iname "*.sh" -exec bash {} \;
        env:
          CHAVE: ${{ inputs.chave }}
          REPO: ${{ inputs.repo }}
