name: Verify PullRequest

on:
  schedule:
    - cron:  '0 23 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
          
      - name: Verify and Send Msg
        shell: bash -O extglob {0}
        run: |
          for i in $(gh repo list --limit 500 --visibility public biglinux | awk '{print $1}'); do 
            open=$(gh pr list -R $i --state open | grep OPEN)
            if [ -n "$open" ];then
              package=$(echo $i | cut -d "/" -f2)
              curl -X POST -H 'Content-Type: application/json' -d '{"chat_id": "${{ secrets.CHAT_ID }}", "text": "☢️ PullRequest encontrado no '$package', https://github.com/'$i'/pulls", "disable_notification": false}' ${{ secrets.MESSAGE_BOT_KEY }}
            fi
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
