name: Verify PullRequest

on:
  schedule:
    - cron:  '0 10 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
          
      - name: Verify and Send Msg
        shell: bash
        run: |
          for i in $(gh repo list --limit 500 --visibility public biglinux | awk '{print $1}'); do 
            open=$(gh pr list -R $i --state open | grep OPEN)
            if [ -n "$open" ];then
              echo "$i"
              # echo "PullRequest encontrado no $(echo $i | cut -d "/" -f2), https://github.com/$i/pulls"
            fi
          done
          
          # echo "LIST"
          # gh repo list --limit 500 --visibility public biglinux
          
          # echo "PR"
          # gh pr list -R biglinux/bigbashview --state open | grep OPEN
          
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
